# -*- coding: utf-8 -*-
"""parametric search

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zLNTBwuyxQch_GcY1YmM2yjII0ni2jGA
"""

n, m = list(map(int, input().split(' ')))
array = list(map(int, input().split()))

start = 0
end = max(array)

result = 0
while(start <= end):
  total = 0
  mid = (start + end) // 2
  for x in array:
    if x > mid:
      total += x - mid
    if total < m:
      end = mid - 1
    else:
      result = mid
      start = mid + 1

print(result)

